use std::error::Error;
use std::fmt;

/// Surface handle representing a drawable surface
#[derive(Debug, Clone, Copy)]
pub struct Surface {
    pub handle: *mut std::ffi::c_void,
    pub width: u32,
    pub height: u32,
    pub scale_factor: f32,
}

/// Common configuration for all embedder types
#[derive(Debug, Clone)]
pub struct EmbedderConfig {
    pub application_name: String,
    pub enable_high_dpi: bool,
    pub vsync: bool,
}

/// Common events for all platforms
#[derive(Debug, Clone)]
pub enum Event {
    Quit,
    Resized { width: u32, height: u32 },
    Moved { x: i32, y: i32 },
    Input(InputEvent),
}

/// Input events that can be generated by the embedder
#[derive(Debug, Clone)]
pub enum InputEvent {
    MouseMove { x: f32, y: f32 },
    MouseButton { button: MouseButton, pressed: bool },
    MouseWheel { delta: f32 },
    Key { key: Key, pressed: bool },
    TextInput(char),
}

/// Mouse button identifiers
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum MouseButton {
    Left,
    Right,
    Middle,
    Button4,
    Button5,
}

/// Keyboard key identifiers
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Key {
    // Add key variants as needed
    Unknown,
    Escape,
    Return,
    Tab,
    Backspace,
    Delete,
    // Arrow keys
    Left,
    Right,
    Up,
    Down,
    // ... more keys
}

/// Error type for embedder operations
#[derive(Debug)]
pub enum EmbedderError {
    InitializationFailed(String),
    InvalidHandle,
    SurfaceCreationFailed(String),
    PlatformError(String),
}

impl fmt::Display for EmbedderError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            EmbedderError::InitializationFailed(msg) => write!(f, "Initialization failed: {}", msg),
            EmbedderError::InvalidHandle => write!(f, "Invalid handle"),
            EmbedderError::SurfaceCreationFailed(msg) => write!(f, "Surface creation failed: {}", msg),
            EmbedderError::PlatformError(msg) => write!(f, "Platform error: {}", msg),
        }
    }
}

impl Error for EmbedderError {}

/// Base embedder trait shared by all platform implementations
pub trait Embedder {
    type Handle: Copy + Clone + PartialEq + Eq + std::hash::Hash;
    
    /// Initialize the embedder with the given configuration
    fn init(&mut self, config: EmbedderConfig) -> Result<(), EmbedderError>;
    
    /// Process pending events
    fn process_events(&mut self) -> Vec<Event>;
    
    /// Check if the embedder is running
    fn is_running(&self) -> bool;
    
    /// Get a surface for rendering
    fn get_surface(&self, handle: Self::Handle) -> Result<Surface, EmbedderError>;
    
    /// Request a redraw
    fn request_redraw(&mut self, handle: Self::Handle);
    
    /// Shutdown the embedder
    fn shutdown(&mut self);
}
