[package]
name = "vectron_app"
version.workspace = true
edition.workspace = true
authors.workspace = true
description = "Application framework for Vectron"
license.workspace = true

[dependencies]
vectron_embedder = { path = "../vectron_embedder" }
vectron_wgpu = { path = "../vectron_wgpu" }
vectron_render = { path = "../vectron_render" }
raw-window-handle = "~0.6.0"
bytemuck = { version = "1.14.0", features = ["derive"] }

[[example]]
name = "basic_window"
path = "examples/basic_window.rs"

[[example]]
name = "wgpu_integration"
path = "examples/wgpu_integration.rs"
